### ISSUE TITLE
Bug report: Unhandled error in Deferred

### ISSUE THREAD

**Issue by f321x** [joinmarket-webui/jam#662]
**Expected behavior**
Exception in logs, coinjoin worked fine but maybe this is some bug either in jam or jm?

**Actual behavior**
```

...
    ],
    "txid": "xxx",
    "nLockTime": xxx,
    "nVersion": 2
}
2023-09-17 11:23:46,661 [INFO]  INFO:Built tx, sending to counterparties.
2023-09-17 11:23:47,683 [INFO]  Updating status to connected for peer xxx.onion:5222.
2023-09-17 11:23:47,684 [INFO]  We, NOT-SERVING-ONION, are calling the handshake callback as client.
2023-09-17 11:23:47,684 [INFO]  Sending this handshake: {"app-name": "joinmarket", "directory": false, "location-string": "NOT-SERVING-ONION", "proto-ver": 5, "features": {}, "nick": "xxx", "network": "mainnet"} to peer xxx.onion:5222
2023-09-17 11:23:48,812 [INFO]  Updating status to connected for peer xxx.onion:5222.
2023-09-17 11:23:48,812 [INFO]  We, NOT-SERVING-ONION, are calling the handshake callback as client.
2023-09-17 11:23:48,812 [INFO]  Sending this handshake: {"app-name": "joinmarket", "directory": false, "location-string": "NOT-SERVING-ONION", "proto-ver": 5, "features": {}, "nick": "xxx", "network": "mainnet"} to peer xxx.onion:5222
2023-09-17 11:23:48,818 [INFO]  Updating status to connected for peer xxx.onion:5222.
2023-09-17 11:23:48,818 [INFO]  We, NOT-SERVING-ONION, are calling the handshake callback as client.
2023-09-17 11:23:48,819 [INFO]  Sending this handshake: {"app-name": "joinmarket", "directory": false, "location-string": "NOT-SERVING-ONION", "proto-ver": 5, "features": {}, "nick": "xxx", "network": "mainnet"} to peer xxx.onion:5222
2023-09-17 11:23:48,820 [INFO]  Updating status to connected for peer xxx.onion:5222.
2023-09-17 11:23:48,820 [INFO]  We, NOT-SERVING-ONION, are calling the handshake callback as client.
2023-09-17 11:23:48,821 [INFO]  Sending this handshake: {"app-name": "joinmarket", "directory": false, "location-string": "NOT-SERVING-ONION", "proto-ver": 5, "features": {}, "nick": "xxx", "network": "mainnet"} to peer xxx.onion:5222
2023-09-17 11:23:49,581 [INFO]  all makers have sent their signatures
2023-09-17 11:23:49,581 [INFO]  INFO:Transaction is valid, signing..
2023-09-17 11:23:49,590 [INFO]  txid = xxx
2023-09-17 11:24:00,830 [INFO]  Removed utxos=
xxx:0 - path: m/84'/0'/0'/0/4, address: xxx, value: xxx
2023-09-17 11:24:00,831 [INFO]  Added utxos=
xxx:2 - path: m/84'/0'/0'/1/1, address: xxx, value: xxx
2023-09-17 11:24:00,842 [INFO]  Transaction seen on network, waiting for confirmation
2023-09-17 11:24:00,842 [INFO]  Coinjoin completed correctly
Unhandled error in Deferred:

Traceback (most recent call last):
--- <exception caught here> ---
  File "/usr/local/lib/python3.9/dist-packages/twisted/internet/defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/src/jmdaemon/jmdaemon/onionmc.py", line 531, in respond_to_connection_failure
    failure.trap(HostUnreachableError, SocksError, GeneralServerFailureError)
  File "/usr/local/lib/python3.9/dist-packages/twisted/python/failure.py", line 476, in trap
    self.raiseException()
  File "/usr/local/lib/python3.9/dist-packages/twisted/python/failure.py", line 500, in raiseException
    raise self.value.with_traceback(self.tb)
twisted.internet.defer.CancelledError: 

Unhandled error in Deferred:

Traceback (most recent call last):
--- <exception caught here> ---
  File "/usr/local/lib/python3.9/dist-packages/twisted/internet/defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/src/jmdaemon/jmdaemon/onionmc.py", line 531, in respond_to_connection_failure
    failure.trap(HostUnreachableError, SocksError, GeneralServerFailureError)
  File "/usr/local/lib/python3.9/dist-packages/twisted/python/failure.py", line 476, in trap
    self.raiseException()
  File "/usr/local/lib/python3.9/dist-packages/twisted/python/failure.py", line 500, in raiseException
    raise self.value.with_traceback(self.tb)
twisted.internet.defer.CancelledError: 

2023-09-17 11:24:01,194 [INFO]  Going to reattempt connection to XXX.onion:5222 in 8.0 seconds.
2023-09-17 11:24:04,222 [INFO]  Updating status to connected for peer XXX.onion:5222.
2023-09-17 11:24:04,222 [INFO]  We, NOT-SERVING-ONION, are calling the handshake callback as client.
```

**Specifications**
  - Version: 0.1.5
  - Platform: Umbrel on Notebook
  - Browser: Librewolf

**Comment by theborakompanioni** [comment]
Hey @f321x, thanks for the report :pray: 

I am not able to move this to https://github.com/JoinMarket-Org/joinmarket-clientserver/issues, which is the better/proper place for issues related to the backend. Would it be possible for you to open the issue there?

(Expecting your backend version to be `v0.9.9`)

**Comment by f321x** [comment]
https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1551
